apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  schemaVersion: v1.0.0
  name: homebrew-tap
  description: Tap for our Homebrew libraries
  annotations:
    github.com/project-slug: Bandwidth/homebrew-tap
  organization: BW
  costCenter: 
  platformType: 
  buildPlatform: N/A
spec:
  type: Service
  owner: github/band-swi
  lifecycle: Prototype
  
