# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Band < Formula
  desc "Bandwidth CLI — manage voice, messaging, numbers, and more from the command line"
  homepage "https://github.com/Bandwidth/cli"
  version "0.1.0-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Bandwidth/cli/releases/download/v0.1.0-beta/band_0.1.0-beta_darwin_amd64.tar.gz"
      sha256 "f6e5650629ac1cdcba87978a466b81a30589ae6de6b6e140d36900b6bfbcc6a7"

      define_method(:install) do
        bin.install "band"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Bandwidth/cli/releases/download/v0.1.0-beta/band_0.1.0-beta_darwin_arm64.tar.gz"
      sha256 "91c0be841b511dbd584ef259e3413716b49e0c5d495de0b6c6a02eb565ce16c4"

      define_method(:install) do
        bin.install "band"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bandwidth/cli/releases/download/v0.1.0-beta/band_0.1.0-beta_linux_amd64.tar.gz"
      sha256 "7f5bbf512582e4f42a5934e32ba89815dc1230110852096c4f350e94151596e5"
      define_method(:install) do
        bin.install "band"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bandwidth/cli/releases/download/v0.1.0-beta/band_0.1.0-beta_linux_arm64.tar.gz"
      sha256 "123f0dcf7c2dcb1df928a90dc6f651e2f57b7b0637b2e38ac3965e074b028be0"
      define_method(:install) do
        bin.install "band"
      end
    end
  end

  test do
    system "#{bin}/band", "version"
  end
end
