# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Band < Formula
  desc "Bandwidth CLI — manage voice, messaging, numbers, and more from the command line"
  homepage "https://github.com/Bandwidth/cli"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Bandwidth/cli/releases/download/v0.0.1-beta/band_0.0.1-beta_darwin_amd64.tar.gz"
      sha256 "daa496b8ed9c1ef4431306de8dec82deebe28d6f1249f90671d673ee32371d06"

      define_method(:install) do
        bin.install "band"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Bandwidth/cli/releases/download/v0.0.1-beta/band_0.0.1-beta_darwin_arm64.tar.gz"
      sha256 "727e036064ea6e8633f87d9081d814221f9f9e4836fa75ea9da6858e147fd57e"

      define_method(:install) do
        bin.install "band"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bandwidth/cli/releases/download/v0.0.1-beta/band_0.0.1-beta_linux_amd64.tar.gz"
      sha256 "4065efca57f284db3d7b53f79542b06a3a38e7c980723c85d626a48d5681401a"
      define_method(:install) do
        bin.install "band"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bandwidth/cli/releases/download/v0.0.1-beta/band_0.0.1-beta_linux_arm64.tar.gz"
      sha256 "9135e75a850c4f4e2131265fb7d7e4b0b679924e8c95d491f1542e03378db674"
      define_method(:install) do
        bin.install "band"
      end
    end
  end

  test do
    system "#{bin}/band", "version"
  end
end
